completed ticket 9
Amir2341/NC-news-project pull request #8
Opened 2022-08-03 11:03 UTC by Amir2341

2022-08-03 11:28 UTC, cjplatten requested changes
Please see comments

2022-08-03 11:28 UTC, cjplatten commented on models/model.js
> +    });
I'm not sure what this error is finding. If the article id exists but there are no comments associated in the databaase, has an error occured?

2022-08-03 11:28 UTC, cjplatten commented on models/model.js
> +    });
It also doesn't look like this was tested.

2022-08-03 13:38 UTC, cjplatten requested changes
Please see comment

2022-08-03 13:38 UTC, cjplatten commented on models/model.js
> +    });
I see what this error is for now. I would argue that you're trying to combine two possible outcomes into one test - one of which is an error and the other which isn't. What happens if the id does exist but has no comments vs what is the id doesn't exist?

2022-08-04 10:36 UTC, corkesw commented
I see the logic for handling the non-existent id... would also be good to see a test for an article with no comment and assert what you would like the api to send back in this case. eg, we'd still get a key of comments but it's value would be an empty array

2022-08-04 13:07 UTC, karlaferry commented on __tests__/app.test.js
> +        expect(body).toEqual({ comments: [] });
I would test the `body.comments.length` here instead of testing this way.

2022-08-04 13:08 UTC, karlaferry approved these changes

2022-08-05 08:44 UTC, merged